export enum TokenType {
  BOOLEAN = "BOOLEAN",
  NULL = "NULL",
  NUMBER = "NUMBER",
  STRING = "STRING",
  COLON = "COLON",
  COMMA = "COMMA",
  BEGIN_ARRAY = "BEGIN_ARRAY",
  END_ARRAY = "END_ARRAY",
  BEGIN_OBJECT = "BEGIN_OBJECT",
  END_OBJECT = "END_OBJECT",
  END_JSON = "END_JSON"
};
